feat: update endpoint /user/all to /user/all/minimal and the format of its response
majority-elite/dobiemon pull request #12
Opened 2023-04-16 06:39 UTC by Godbell

3 commits

feat: update endpoint /user/all to only return needed data

refactor: specify minimal data needed as an interface and bot gateway only responsible for getting client data
feat: update endpoint user/all to user/all/minimal to clarify the format it provides

2023-04-16 11:07 UTC, aube-dev requested changes

2023-04-16 11:07 UTC, aube-dev commented on src/user/user.controller.ts
> +  async getAllUserIDs(): Promise<MinimalUserInfo[]> {
```suggestion
  async getAllMinimalUsers(): Promise<MinimalUserInfo[]> {
```

2023-04-16 11:07 UTC, aube-dev commented on src/user/user-info.inferface.ts
> +export interface MinimalUserInfo {
~`Info` 붙이는 대신 `MinimalUser`로 심플하게 가면 어떨까요?
```suggestion
export interface MinimalUser {
```

2023-04-16 11:07 UTC, aube-dev commented on src/user/user.service.ts
> +  async getAllUsersInfoMinimal(): Promise<MinimalUserInfo[]> {
```suggestion
  async getAllMinimalUsers(): Promise<MinimalUserInfo[]> {
```

2023-04-16 11:07 UTC, aube-dev commented on src/bot/bot.service.ts
> +  }
`BotService`에서는 바로 `MinimalUserInfo`로 가지 말고 일단 유저 정보 전체를 넘겨주는 게 어떨까요? 혹시 유저 정보가 추가로 필요할 수도 있으니까요!

```ts
/** bot accounts are excluded */
async getAllUsers() {
  const guild = await this.getGuild();
  const users = await guild.members.fetch();
  return users.filter((member) => !member.user.bot);
}
```

2023-04-16 11:19 UTC, Godbell commented on src/user/user.controller.ts
> +  async getAllUserIDs(): Promise<MinimalUserInfo[]> {
`getAllMinimalUsers`라고 했을 때 Mimimal Users라는 어휘의 의미 혼동을 막기 위해 ,`getAllUsersMinimal`은 어떨까요?

2023-04-16 11:53 UTC, aube-dev commented on src/user/user.controller.ts
> +  async getAllUserIDs(): Promise<MinimalUserInfo[]> {
그것도 좋을 것 같아요! 뭔가 조금 더 근본적인 이름이 있어도 좋을 것 같은데... `UserProfile`...? 이런 거...?

2023-04-17 16:49 UTC, aube-dev approved these changes
👍

2023-04-17 16:56 UTC, merged